### ISSUE TITLE
Display only the results

### ISSUE THREAD

**Issue by ncarboni** [daizutabi/pheasant#12]
I was wondering if it would be possible to use the pheasant to only display the results of the exxecution of the code in the codeblock. 
Currently I insert a python script to create a table based on the result of a query to a database. I would like to display the resulting table (the one within the red border in the attached image) but not the code used to create it in the page.

Would that be possible?

Image example:
![query](https://user-images.githubusercontent.com/5669838/83921653-15675480-a77f-11ea-98bd-17ebef5b60c2.png)

**Comment by daizutabi** [comment]
Use `hide-input` option. (Sorry, this option hasn't been documented.)

You can omit `print` function to render the dataframe in a table format.

You can also use inline-mode like `{{ df }}`. If you need a caption, `#Table` header is helpful.

<img width="462" alt="img1" src="https://user-images.githubusercontent.com/17495937/83928628-5be2a080-a7cb-11ea-8f43-25726a230a00.png">

<img width="411" alt="img2" src="https://user-images.githubusercontent.com/17495937/83928638-6309ae80-a7cb-11ea-8a2e-34d7abc1b107.png">

**Comment by ncarboni** [comment]
Perfect, you answered also the natural follow up question :-)
Thank you! I obtained the exact results I was searching for!
