### ISSUE TITLE
Just run python withiin brackets

### ISSUE THREAD

**Issue by kamaing** [daizutabi/pheasant#8]
Is it possible just to run python in md-file within the brackets {{ }}?
Is it possible to avoid numbering headers and changing naming in the navigation?

<pre>
plugins:
  - pheasant:
      header:
        disabled: true
</pre>

does not lead to the desired output.

Thanks.

**Comment by daizutabi** [comment]
Yes, it is possible to run Python with inline-code only.
Please check a minimal example below:


<img width="645" alt="code" src="https://user-images.githubusercontent.com/17495937/77798160-b36edc80-70b5-11ea-979a-bf09b3e0f613.png">

<img width="335" alt="sample" src="https://user-images.githubusercontent.com/17495937/77798197-c5507f80-70b5-11ea-97a5-c4db996663f1.png">
