### ISSUE TITLE
Nav numbers start appearing when using pheasant

### ISSUE THREAD

**Issue by epicfaace** [daizutabi/pheasant#9]
I'm using mkdocs 1.1. My nav initially looks like this:

![image](https://user-images.githubusercontent.com/1689183/81484952-c679de00-9217-11ea-8350-32ae9d196aac.png)

However, when I enable pheasant, it looks like this:

![image](https://user-images.githubusercontent.com/1689183/81484969-df828f00-9217-11ea-848d-c04e39c55a58.png)

Here's my mkdocs.yml: https://github.com/rjsf-team/react-jsonschema-form/blob/bdf81a70fc90f0f32b8a4e3ee5d8a4b0328d817d/mkdocs.yml#L15

**Comment by daizutabi** [comment]
I changed the default behavior of nav numbering (False by default). Please update pheasant to version 2.5.2  or later.

**Comment by epicfaace** [comment]
Thanks!
